import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Dark from "./component/dark";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Arclight's Profile",
  description: "Generated by create next app",
};
 
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Dark>
          <main>
            {children}
          </main>
        </Dark>
      </body>
    </html>
  );
}
